### ISSUE TITLE
module incorrectly determines linux VM for desktop flavours of Windows 

### ISSUE THREAD

**Issue by Xyon** [Azure/terraform-azurerm-compute#56]
When using the compute provider like so:

    module "client" {
      source              = "Azure/compute/azurerm"
      location            = "${azurerm_resource_group.rg.location}"
      resource_group_name = "${azurerm_resource_group.rg.name}"
      admin_password      = "ReallySecurePassWord"
    
      public_ip_dns       = [""]
      nb_public_ip        = 0
    
      vm_hostname         = "client"
      vm_os_publisher     = "MicrosoftWindowsDesktop"
      vm_os_offer         = "Windows-10"
      vm_os_sku           = "RS3-Pro"
      vm_size             = "Standard_B2MS"
      is_windows_image    = true
      vnet_subnet_id      = "${module.network.vnet_subnets[0]}"
    }

Terraform decides that this should be a Linux machine, and fails because I don't have an "id_rsa.pub" in the usual location:

    $ terraform plan
    
    Error: module.client.azurerm_virtual_machine.vm-linux: 1 error(s) occurred:
    
    * module.client.azurerm_virtual_machine.vm-linux: file: open /home/xyon/.ssh/id_rsa.pub: no such file or directory in:
    
    ${file("${var.ssh_key}")}

I have also got two "server" flavour blocks, thus:

    module "servers" {
      source              = "Azure/compute/azurerm"
      location            = "${azurerm_resource_group.rg.location}"
      resource_group_name = "${azurerm_resource_group.rg.name}"
      admin_password      = "EvenMoreSecurePassWord"

      nb_instances        = 2
      public_ip_dns       = [""]
      nb_public_ip        = 0

      vm_hostname         = "server"
      vm_os_publisher     = "MicrosoftWindowsServer"
      vm_os_offer         = "WindowsServer"
      vm_os_sku           = "2016-Datacenter"
      vm_size             = "Standard_B2MS"
      is_windows_image    = true
      vnet_subnet_id      = "${module.network.vnet_subnets[0]}"
    }

This works okay in as much as selecting "Windows" for the vm type. Note that I've tried to force the issue in both cases by supplying "is_windows_image = true" in both blocks, which made no difference.

Looking at the module, it seems like the logic only deals with WindowsServer variants:

`resource "azurerm_virtual_machine" "vm-windows" {
  count                         = "${(((var.vm_os_id != "" && var.is_windows_image == "true") || contains(list("${var.vm_os_simple}","${var.vm_os_offer}"), "WindowsServer")) && var.data_disk == "false") ? var.nb_instances : 0}"`

And likewise the linux resource is happy to accept anything that isn't a Windows Server block:

`resource "azurerm_virtual_machine" "vm-linux-with-datadisk" {
  count                         = "${!contains(list("${var.vm_os_simple}","${var.vm_os_offer}"), "WindowsServer")  && var.is_windows_image != "true"  && var.data_disk == "true" ? var.nb_instances : 0}"
`

I suggest the logic could be improved here to reject any image with "MicrosoftWindows*" in the publisher, assuming only Windows images are released with these publishers. Unfortunately, a glob syntax seemed to not work, so I settled for changing the module logic locally to:

`resource "azurerm_virtual_machine" "vm-windows" {
  count                         = "${(((var.vm_os_id != "" && var.is_windows_image == "true") || (contains(list("${var.vm_os_simple}","${var.vm_os_publisher}"), "MicrosoftWindowsDesktop") || contains(list("${var.vm_os_simple}","${var.vm_os_publisher}"), "MicrosoftWindowsServer"))) && var.data_disk == "false") ? var.nb_instances : 0}"`

Which seems to resolve the problem (once I adjust the inverse logic accordingly in the linux image section).

**Comment by Xyon** [comment]
This appears to no longer be the case, but instead, Terraform quietly decided that my "Client" VM shouldn't actually make a VM at all!

**Comment by crobo1337** [comment]
I think i'm running in to a similar issue, if not the same exact issue. I'm trying to deploy a few test VMs per the readme. Only changes I've made are some variable interpolation and for some reason TF is trying to build a linux box instead of a windows one.

```module "windowsservers" {
    source              = "Azure/compute/azurerm"
    version             = "1.2.0"
    resource_group_name = "${azurerm_resource_group.ResGrp.name}"
    location            = "${var.location}"
    vm_hostname         = "${var.namespace}-win-test"
    admin_password      = "${random_string.win_pass.result}"
    public_ip_dns       = ["${var.namespace}-win-test-1", "${var.namespace}-win-test-2"]
    nb_public_ip        = "2"
    remote_port         = "3389"
    nb_instances        = "2"
    vm_os_publisher     = "MicrosoftWindowsServer"
    vm_os_offer         = "WindowsServer"
    vm_os_sku           = "2012-R2-Datacenter"
    vm_size             = "Standard_DS2_V2"
    vnet_subnet_id      = "${module.network.vnet_subnets[0]}"
    tags                = {
      Environment = "${var.environment}"
      Owner= "${var.owner}"
      Application= "${var.application}"
      BuiltBy= "terraform"
      }
    }
```

Results in a TF plan of

```
+ module.windowsservers.azurerm_virtual_machine.vm-linux[1]
      id:                                                               <computed>
      availability_set_id:                                              "/subscriptions/0fa3340e-f977-4701-9748-c0cf815db6a9/resourcegroups/gk-1-rg/providers/microsoft.compute/availabilitysets/gk-1-win-test-avset"
      boot_diagnostics.#:                                               "1"
      boot_diagnostics.0.enabled:                                       "false"
      delete_data_disks_on_termination:                                 "false"
      delete_os_disk_on_termination:                                    "false"
      identity.#:                                                       <computed>
      location:                                                         "eastus"
      name:                                                             "gk-1-win-test1"
...
....
```

and eventually errors with:

```
* azurerm_virtual_machine.vm-linux.0: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="The value of parameter linuxConfiguration is invalid." Target="linuxConfiguration"
```

**Comment by Xyon** [comment]
I think I fixed this with #73 and #72; We've been pulling the module directly from git instead of taking the 1.2.0 release until those PRs are released.

If you adapt the source line to source the git repo, you can do that too, thus;
`source              = "github.com/Azure/terraform-azurerm-compute.git"`

**Comment by sskoklev** [comment]
Hi @Xyon 
Im running the below, basically the simple usage scenario, on v0.11.11, pulling from the git repo as suggested and I still get the error. Any suggestions?

_Error: module.windowsservers.azurerm_virtual_machine.vm-linux: 1 error(s) occurred:
* module.windowsservers.azurerm_virtual_machine.vm-linux: file: open C:\Users\sskoklev\.ssh\id_rsa.pub: The system cannot find the path specified. in:
${file("${var.ssh_key}")}_

module "windowsservers" {
    source              = "github.com/Azure/terraform-azurerm-compute.git" 
    location            = "West US 2"
    vm_hostname         = "mywinvm" 
    admin_password      = "ComplxP@ssw0rd!"
    vm_os_simple        = "WindowsServer"
    is_windows_image    = true
    public_ip_dns       = ["winsimplevmips"] // change to a unique name per datacenter region
    vnet_subnet_id      = "${module.network.vnet_subnets[0]}"
  }

**Comment by Xyon** [comment]
No idea off the top of my head, sorry. I'll need to debug it with the vm_os_simple lines.

**Comment by Xyon** [comment]
No idea off the top of my head, sorry. I'll need to debug it with the vm_os_simple lines.

**Comment by yupwei68** [comment]
Hi @Xyon , thanks for opening this issue. On fact,` is_windows_image =true` is required if you want to create a windows vm, which will prevent you from creating a linux vm. I'd like to close this issue temporarily.
